application: Sherrington Kirkpatrick (SK) model (#208)
* Added Sherrington Kirkpatrick (SK) model to applications

* update .gitignore

update .gitignore

* Update qiskit_optimization/applications/SK_model.py

removed unnecessary variable

Co-authored-by: dlasecki <dal@zurich.ibm.com>

* Update qiskit_optimization/applications/SK_model.py

typo

Co-authored-by: dlasecki <dal@zurich.ibm.com>

* Update qiskit_optimization/applications/SK_model.py

typo

Co-authored-by: dlasecki <dal@zurich.ibm.com>

* Update qiskit_optimization/applications/SK_model.py

typo

Co-authored-by: dlasecki <dal@zurich.ibm.com>

* Update qiskit_optimization/applications/SK_model.py

Co-authored-by: dlasecki <dal@zurich.ibm.com>

* Update qiskit_optimization/applications/SK_model.py

Co-authored-by: dlasecki <dal@zurich.ibm.com>

* Update qiskit_optimization/applications/SK_model.py

Co-authored-by: dlasecki <dal@zurich.ibm.com>

* subtests

* default number of places in assertAlmostEqual

* with subtests

* added math formatting

* Update .gitignore

removed extra line.

* Update .pylintdict

added SK names and words to the dictionary

* interpret return type

* interpret -- changed to match interpret of other applications in this module. (btw, I still think they should return also the value of the problem)

* removed unused import

* test interpret corrected

* test interpret corrected

* black, removed optional from rng.

* rng default changed to np.random.RandomState(0)

* SKModel exposed in __init__.py

* Reformated according to the lint.

* Removed unused Optional.

* Update qiskit_optimization/applications/sk_model.py

configuration interpreted through list comprehension

Co-authored-by: Takashi Imamichi <31178928+t-imamichi@users.noreply.github.com>

* SKmodel added to __init__.py

* Update qiskit_optimization/applications/sk_model.py

succinct definition of variables

Co-authored-by: Takashi Imamichi <31178928+t-imamichi@users.noreply.github.com>

* SKModel removed rng setter.

* SKModel pseudo-rng changes.

* SKModel pseudo-rng corrections.

* SKModel pseudo-rng corrections. I am not sure how to correctly deal with:
qiskit_optimization/applications/sk_model.py:55: error: Incompatible types in assignment
(expression has type "Generator", variable has type Module)
type ignored.

* Update qiskit_optimization/applications/sk_model.py

default np.random changed to np.random.default_rng()

Co-authored-by: Takashi Imamichi <31178928+t-imamichi@users.noreply.github.com>

* new_instance() changed to new_disorder()
added release note

* some format

* release note update (trying to fix the checks not sure how..)

* release note update: search for the problem (not sure how to do it locally).

* release note update 2: search for the problem --- minimal text.

* release note update 3: search for the problem --- example.

* release note update --- minimum release text.

* new_disorder -> disorder
allowed seed in constructor

* longer release notes. test, might fail checks.

* without check for int.

* release notes.

* typo

* Update qiskit_optimization/applications/sk_model.py

removed boring comment

Co-authored-by: Steve Wood <40241007+woodsp-ibm@users.noreply.github.com>

* test init comment indenting.... not sure if it works.

* comments improvement.

* comments long lines.

* typos

* getter number of sites.

* num_of_sites -> num_sites

* (.) -> (<seed>)

Co-authored-by: dlasecki <dal@zurich.ibm.com>
Co-authored-by: Steve Wood <40241007+woodsp-ibm@users.noreply.github.com>
Co-authored-by: Takashi Imamichi <31178928+t-imamichi@users.noreply.github.com>